// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvslga13rw84Fhixpsey5OK_6M_1gfJeM',
    appId: '1:864261407690:web:2f0021cee7224aaa8c0533',
    messagingSenderId: '864261407690',
    projectId: 'drivers-95828',
    authDomain: 'drivers-95828.firebaseapp.com',
    storageBucket: 'drivers-95828.firebasestorage.app',
    measurementId: 'G-EC41WGYY73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkFlKIvVR7-hCXt3PJ-oIU5b_tedHZlUw',
    appId: '1:864261407690:android:596620446f4b4e2a8c0533',
    messagingSenderId: '864261407690',
    projectId: 'drivers-95828',
    storageBucket: 'drivers-95828.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuIpoemVl14GlOwhhSoqhdybjpxK4BSFY',
    appId: '1:864261407690:ios:af549e0a4a6e80e68c0533',
    messagingSenderId: '864261407690',
    projectId: 'drivers-95828',
    storageBucket: 'drivers-95828.firebasestorage.app',
    iosBundleId: 'com.example.driversApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuIpoemVl14GlOwhhSoqhdybjpxK4BSFY',
    appId: '1:864261407690:ios:af549e0a4a6e80e68c0533',
    messagingSenderId: '864261407690',
    projectId: 'drivers-95828',
    storageBucket: 'drivers-95828.firebasestorage.app',
    iosBundleId: 'com.example.driversApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvslga13rw84Fhixpsey5OK_6M_1gfJeM',
    appId: '1:864261407690:web:d760242c26b270f88c0533',
    messagingSenderId: '864261407690',
    projectId: 'drivers-95828',
    authDomain: 'drivers-95828.firebaseapp.com',
    storageBucket: 'drivers-95828.firebasestorage.app',
    measurementId: 'G-CTMPYRXWZV',
  );

}