// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANxtCrpJWUJn1UQCoPMczopabx_Du0Ycs',
    appId: '1:215240400915:web:83293736940179d67c5fe6',
    messagingSenderId: '215240400915',
    projectId: 'drivers-a58a4',
    authDomain: 'drivers-a58a4.firebaseapp.com',
    storageBucket: 'drivers-a58a4.firebasestorage.app',
    measurementId: 'G-NQ9G0FQMRQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmg3RR7MqzSrHQ1GgBcuobOYv_jDm0RVo',
    appId: '1:215240400915:android:853537c9560cc04f7c5fe6',
    messagingSenderId: '215240400915',
    projectId: 'drivers-a58a4',
    storageBucket: 'drivers-a58a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUxBeE0xN5oOKkWd0wsIV_qBEWYj0PuUM',
    appId: '1:215240400915:ios:dbb1d58c68b916857c5fe6',
    messagingSenderId: '215240400915',
    projectId: 'drivers-a58a4',
    storageBucket: 'drivers-a58a4.firebasestorage.app',
    iosBundleId: 'com.example.driversApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUxBeE0xN5oOKkWd0wsIV_qBEWYj0PuUM',
    appId: '1:215240400915:ios:dbb1d58c68b916857c5fe6',
    messagingSenderId: '215240400915',
    projectId: 'drivers-a58a4',
    storageBucket: 'drivers-a58a4.firebasestorage.app',
    iosBundleId: 'com.example.driversApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANxtCrpJWUJn1UQCoPMczopabx_Du0Ycs',
    appId: '1:215240400915:web:4d3e1aebfec0a6f57c5fe6',
    messagingSenderId: '215240400915',
    projectId: 'drivers-a58a4',
    authDomain: 'drivers-a58a4.firebaseapp.com',
    storageBucket: 'drivers-a58a4.firebasestorage.app',
    measurementId: 'G-DFQN04KH0S',
  );

}